// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udmMessage.proto

#include "udmMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace UDM {
PROTOBUF_CONSTEXPR UDMMessage::UDMMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.topicname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.variablename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.variableunit_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sourcename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_type_)*/0
  , /*decltype(_impl_.lockstat_)*/0
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UDMMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UDMMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UDMMessageDefaultTypeInternal() {}
  union {
    UDMMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UDMMessageDefaultTypeInternal _UDMMessage_default_instance_;
}  // namespace UDM
static ::_pb::Metadata file_level_metadata_udmMessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_udmMessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_udmMessage_2eproto = nullptr;

const uint32_t TableStruct_udmMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.message_type_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.topicname_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.variablename_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.variableunit_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.sourcename_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.lockstat_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.value_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::UDM::UDMMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::UDM::_UDMMessage_default_instance_._instance,
};

const char descriptor_table_protodef_udmMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020udmMessage.proto\022\003UDM\"\251\001\n\nUDMMessage\022\024"
  "\n\014message_type\030\001 \001(\005\022\021\n\ttopicName\030\002 \001(\t\022"
  "\024\n\014variableName\030\003 \001(\t\022\024\n\014variableUnit\030\004 "
  "\001(\t\022\022\n\nsourceName\030\005 \001(\t\022\020\n\010lockStat\030\006 \001("
  "\005\022\021\n\ttimestamp\030\007 \001(\004\022\r\n\005value\030\010 \001(\014b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_udmMessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_udmMessage_2eproto = {
    false, false, 203, descriptor_table_protodef_udmMessage_2eproto,
    "udmMessage.proto",
    &descriptor_table_udmMessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_udmMessage_2eproto::offsets,
    file_level_metadata_udmMessage_2eproto, file_level_enum_descriptors_udmMessage_2eproto,
    file_level_service_descriptors_udmMessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_udmMessage_2eproto_getter() {
  return &descriptor_table_udmMessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_udmMessage_2eproto(&descriptor_table_udmMessage_2eproto);
namespace UDM {

// ===================================================================

class UDMMessage::_Internal {
 public:
};

UDMMessage::UDMMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:UDM.UDMMessage)
}
UDMMessage::UDMMessage(const UDMMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UDMMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.topicname_){}
    , decltype(_impl_.variablename_){}
    , decltype(_impl_.variableunit_){}
    , decltype(_impl_.sourcename_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.message_type_){}
    , decltype(_impl_.lockstat_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.topicname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.topicname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_topicname().empty()) {
    _this->_impl_.topicname_.Set(from._internal_topicname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.variablename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.variablename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_variablename().empty()) {
    _this->_impl_.variablename_.Set(from._internal_variablename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.variableunit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.variableunit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_variableunit().empty()) {
    _this->_impl_.variableunit_.Set(from._internal_variableunit(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sourcename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sourcename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sourcename().empty()) {
    _this->_impl_.sourcename_.Set(from._internal_sourcename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.message_type_, &from._impl_.message_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.message_type_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:UDM.UDMMessage)
}

inline void UDMMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.topicname_){}
    , decltype(_impl_.variablename_){}
    , decltype(_impl_.variableunit_){}
    , decltype(_impl_.sourcename_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.message_type_){0}
    , decltype(_impl_.lockstat_){0}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.topicname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.topicname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.variablename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.variablename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.variableunit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.variableunit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sourcename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sourcename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UDMMessage::~UDMMessage() {
  // @@protoc_insertion_point(destructor:UDM.UDMMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UDMMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.topicname_.Destroy();
  _impl_.variablename_.Destroy();
  _impl_.variableunit_.Destroy();
  _impl_.sourcename_.Destroy();
  _impl_.value_.Destroy();
}

void UDMMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UDMMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:UDM.UDMMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.topicname_.ClearToEmpty();
  _impl_.variablename_.ClearToEmpty();
  _impl_.variableunit_.ClearToEmpty();
  _impl_.sourcename_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  ::memset(&_impl_.message_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.message_type_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UDMMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 message_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.message_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string topicName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_topicname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UDM.UDMMessage.topicName"));
        } else
          goto handle_unusual;
        continue;
      // string variableName = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_variablename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UDM.UDMMessage.variableName"));
        } else
          goto handle_unusual;
        continue;
      // string variableUnit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_variableunit();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UDM.UDMMessage.variableUnit"));
        } else
          goto handle_unusual;
        continue;
      // string sourceName = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_sourcename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UDM.UDMMessage.sourceName"));
        } else
          goto handle_unusual;
        continue;
      // int32 lockStat = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.lockstat_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes value = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UDMMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UDM.UDMMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_type = 1;
  if (this->_internal_message_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_message_type(), target);
  }

  // string topicName = 2;
  if (!this->_internal_topicname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_topicname().data(), static_cast<int>(this->_internal_topicname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UDM.UDMMessage.topicName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_topicname(), target);
  }

  // string variableName = 3;
  if (!this->_internal_variablename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_variablename().data(), static_cast<int>(this->_internal_variablename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UDM.UDMMessage.variableName");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_variablename(), target);
  }

  // string variableUnit = 4;
  if (!this->_internal_variableunit().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_variableunit().data(), static_cast<int>(this->_internal_variableunit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UDM.UDMMessage.variableUnit");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_variableunit(), target);
  }

  // string sourceName = 5;
  if (!this->_internal_sourcename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sourcename().data(), static_cast<int>(this->_internal_sourcename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UDM.UDMMessage.sourceName");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_sourcename(), target);
  }

  // int32 lockStat = 6;
  if (this->_internal_lockstat() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_lockstat(), target);
  }

  // uint64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(7, this->_internal_timestamp(), target);
  }

  // bytes value = 8;
  if (!this->_internal_value().empty()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UDM.UDMMessage)
  return target;
}

size_t UDMMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UDM.UDMMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string topicName = 2;
  if (!this->_internal_topicname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_topicname());
  }

  // string variableName = 3;
  if (!this->_internal_variablename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_variablename());
  }

  // string variableUnit = 4;
  if (!this->_internal_variableunit().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_variableunit());
  }

  // string sourceName = 5;
  if (!this->_internal_sourcename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sourcename());
  }

  // bytes value = 8;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_value());
  }

  // int32 message_type = 1;
  if (this->_internal_message_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_message_type());
  }

  // int32 lockStat = 6;
  if (this->_internal_lockstat() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_lockstat());
  }

  // uint64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UDMMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UDMMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UDMMessage::GetClassData() const { return &_class_data_; }


void UDMMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UDMMessage*>(&to_msg);
  auto& from = static_cast<const UDMMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UDM.UDMMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_topicname().empty()) {
    _this->_internal_set_topicname(from._internal_topicname());
  }
  if (!from._internal_variablename().empty()) {
    _this->_internal_set_variablename(from._internal_variablename());
  }
  if (!from._internal_variableunit().empty()) {
    _this->_internal_set_variableunit(from._internal_variableunit());
  }
  if (!from._internal_sourcename().empty()) {
    _this->_internal_set_sourcename(from._internal_sourcename());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_message_type() != 0) {
    _this->_internal_set_message_type(from._internal_message_type());
  }
  if (from._internal_lockstat() != 0) {
    _this->_internal_set_lockstat(from._internal_lockstat());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UDMMessage::CopyFrom(const UDMMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UDM.UDMMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UDMMessage::IsInitialized() const {
  return true;
}

void UDMMessage::InternalSwap(UDMMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.topicname_, lhs_arena,
      &other->_impl_.topicname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.variablename_, lhs_arena,
      &other->_impl_.variablename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.variableunit_, lhs_arena,
      &other->_impl_.variableunit_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sourcename_, lhs_arena,
      &other->_impl_.sourcename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.timestamp_)
      + sizeof(UDMMessage::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.message_type_)>(
          reinterpret_cast<char*>(&_impl_.message_type_),
          reinterpret_cast<char*>(&other->_impl_.message_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UDMMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_udmMessage_2eproto_getter, &descriptor_table_udmMessage_2eproto_once,
      file_level_metadata_udmMessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace UDM
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::UDM::UDMMessage*
Arena::CreateMaybeMessage< ::UDM::UDMMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UDM::UDMMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
