// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: udmMessage.proto
// Protobuf C++ Version: 5.29.5

#include "udmMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UDM {

inline constexpr UDMMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : topicname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        variablename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        variableunit_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sourcename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_type_{0},
        lockstat_{0},
        timestamp_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UDMMessage::UDMMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UDMMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UDMMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UDMMessageDefaultTypeInternal() {}
  union {
    UDMMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UDMMessageDefaultTypeInternal _UDMMessage_default_instance_;
}  // namespace UDM
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_udmMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_udmMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_udmMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.message_type_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.topicname_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.variablename_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.variableunit_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.sourcename_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.lockstat_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::UDM::UDMMessage, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::UDM::UDMMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::UDM::_UDMMessage_default_instance_._instance,
};
const char descriptor_table_protodef_udmMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020udmMessage.proto\022\003UDM\"\251\001\n\nUDMMessage\022\024"
    "\n\014message_type\030\001 \001(\005\022\021\n\ttopicName\030\002 \001(\t\022"
    "\024\n\014variableName\030\003 \001(\t\022\024\n\014variableUnit\030\004 "
    "\001(\t\022\022\n\nsourceName\030\005 \001(\t\022\020\n\010lockStat\030\006 \001("
    "\005\022\021\n\ttimestamp\030\007 \001(\004\022\r\n\005value\030\010 \001(\014b\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_udmMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_udmMessage_2eproto = {
    false,
    false,
    203,
    descriptor_table_protodef_udmMessage_2eproto,
    "udmMessage.proto",
    &descriptor_table_udmMessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_udmMessage_2eproto::offsets,
    file_level_enum_descriptors_udmMessage_2eproto,
    file_level_service_descriptors_udmMessage_2eproto,
};
namespace UDM {
// ===================================================================

class UDMMessage::_Internal {
 public:
};

UDMMessage::UDMMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UDM.UDMMessage)
}
inline PROTOBUF_NDEBUG_INLINE UDMMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::UDM::UDMMessage& from_msg)
      : topicname_(arena, from.topicname_),
        variablename_(arena, from.variablename_),
        variableunit_(arena, from.variableunit_),
        sourcename_(arena, from.sourcename_),
        value_(arena, from.value_),
        _cached_size_{0} {}

UDMMessage::UDMMessage(
    ::google::protobuf::Arena* arena,
    const UDMMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UDMMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, message_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, message_type_),
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, message_type_) +
               sizeof(Impl_::timestamp_));

  // @@protoc_insertion_point(copy_constructor:UDM.UDMMessage)
}
inline PROTOBUF_NDEBUG_INLINE UDMMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : topicname_(arena),
        variablename_(arena),
        variableunit_(arena),
        sourcename_(arena),
        value_(arena),
        _cached_size_{0} {}

inline void UDMMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, message_type_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, message_type_) +
               sizeof(Impl_::timestamp_));
}
UDMMessage::~UDMMessage() {
  // @@protoc_insertion_point(destructor:UDM.UDMMessage)
  SharedDtor(*this);
}
inline void UDMMessage::SharedDtor(MessageLite& self) {
  UDMMessage& this_ = static_cast<UDMMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.topicname_.Destroy();
  this_._impl_.variablename_.Destroy();
  this_._impl_.variableunit_.Destroy();
  this_._impl_.sourcename_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UDMMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UDMMessage(arena);
}
constexpr auto UDMMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UDMMessage),
                                            alignof(UDMMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UDMMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UDMMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UDMMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UDMMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UDMMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UDMMessage>(), &UDMMessage::ByteSizeLong,
            &UDMMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_._cached_size_),
        false,
    },
    &UDMMessage::kDescriptorMethods,
    &descriptor_table_udmMessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UDMMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 74, 2> UDMMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UDM::UDMMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes value = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.value_)}},
    // int32 message_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UDMMessage, _impl_.message_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.message_type_)}},
    // string topicName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.topicname_)}},
    // string variableName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.variablename_)}},
    // string variableUnit = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.variableunit_)}},
    // string sourceName = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.sourcename_)}},
    // int32 lockStat = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UDMMessage, _impl_.lockstat_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.lockstat_)}},
    // uint64 timestamp = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UDMMessage, _impl_.timestamp_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 message_type = 1;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.message_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string topicName = 2;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.topicname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string variableName = 3;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.variablename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string variableUnit = 4;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.variableunit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string sourceName = 5;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.sourcename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 lockStat = 6;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.lockstat_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // uint64 timestamp = 7;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bytes value = 8;
    {PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\11\14\14\12\0\0\0\0\0\0\0\0\0\0"
    "UDM.UDMMessage"
    "topicName"
    "variableName"
    "variableUnit"
    "sourceName"
  }},
};

PROTOBUF_NOINLINE void UDMMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:UDM.UDMMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.topicname_.ClearToEmpty();
  _impl_.variablename_.ClearToEmpty();
  _impl_.variableunit_.ClearToEmpty();
  _impl_.sourcename_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  ::memset(&_impl_.message_type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.message_type_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UDMMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UDMMessage& this_ = static_cast<const UDMMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UDMMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UDMMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:UDM.UDMMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 message_type = 1;
          if (this_._internal_message_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_message_type(), target);
          }

          // string topicName = 2;
          if (!this_._internal_topicname().empty()) {
            const std::string& _s = this_._internal_topicname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UDM.UDMMessage.topicName");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string variableName = 3;
          if (!this_._internal_variablename().empty()) {
            const std::string& _s = this_._internal_variablename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UDM.UDMMessage.variableName");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string variableUnit = 4;
          if (!this_._internal_variableunit().empty()) {
            const std::string& _s = this_._internal_variableunit();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UDM.UDMMessage.variableUnit");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string sourceName = 5;
          if (!this_._internal_sourcename().empty()) {
            const std::string& _s = this_._internal_sourcename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UDM.UDMMessage.sourceName");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // int32 lockStat = 6;
          if (this_._internal_lockstat() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_lockstat(), target);
          }

          // uint64 timestamp = 7;
          if (this_._internal_timestamp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                7, this_._internal_timestamp(), target);
          }

          // bytes value = 8;
          if (!this_._internal_value().empty()) {
            const std::string& _s = this_._internal_value();
            target = stream->WriteBytesMaybeAliased(8, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:UDM.UDMMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UDMMessage::ByteSizeLong(const MessageLite& base) {
          const UDMMessage& this_ = static_cast<const UDMMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UDMMessage::ByteSizeLong() const {
          const UDMMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:UDM.UDMMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string topicName = 2;
            if (!this_._internal_topicname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_topicname());
            }
            // string variableName = 3;
            if (!this_._internal_variablename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_variablename());
            }
            // string variableUnit = 4;
            if (!this_._internal_variableunit().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_variableunit());
            }
            // string sourceName = 5;
            if (!this_._internal_sourcename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sourcename());
            }
            // bytes value = 8;
            if (!this_._internal_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_value());
            }
            // int32 message_type = 1;
            if (this_._internal_message_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_message_type());
            }
            // int32 lockStat = 6;
            if (this_._internal_lockstat() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_lockstat());
            }
            // uint64 timestamp = 7;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_timestamp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UDMMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UDMMessage*>(&to_msg);
  auto& from = static_cast<const UDMMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UDM.UDMMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_topicname().empty()) {
    _this->_internal_set_topicname(from._internal_topicname());
  }
  if (!from._internal_variablename().empty()) {
    _this->_internal_set_variablename(from._internal_variablename());
  }
  if (!from._internal_variableunit().empty()) {
    _this->_internal_set_variableunit(from._internal_variableunit());
  }
  if (!from._internal_sourcename().empty()) {
    _this->_internal_set_sourcename(from._internal_sourcename());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_message_type() != 0) {
    _this->_impl_.message_type_ = from._impl_.message_type_;
  }
  if (from._internal_lockstat() != 0) {
    _this->_impl_.lockstat_ = from._impl_.lockstat_;
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UDMMessage::CopyFrom(const UDMMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UDM.UDMMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UDMMessage::InternalSwap(UDMMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.topicname_, &other->_impl_.topicname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.variablename_, &other->_impl_.variablename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.variableunit_, &other->_impl_.variableunit_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sourcename_, &other->_impl_.sourcename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.timestamp_)
      + sizeof(UDMMessage::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(UDMMessage, _impl_.message_type_)>(
          reinterpret_cast<char*>(&_impl_.message_type_),
          reinterpret_cast<char*>(&other->_impl_.message_type_));
}

::google::protobuf::Metadata UDMMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UDM
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_udmMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
