// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topicList.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_topicList_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_topicList_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_topicList_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_topicList_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_topicList_2eproto;
namespace UDM {
class Node;
struct NodeDefaultTypeInternal;
extern NodeDefaultTypeInternal _Node_default_instance_;
class topicList;
struct topicListDefaultTypeInternal;
extern topicListDefaultTypeInternal _topicList_default_instance_;
}  // namespace UDM
PROTOBUF_NAMESPACE_OPEN
template<> ::UDM::Node* Arena::CreateMaybeMessage<::UDM::Node>(Arena*);
template<> ::UDM::topicList* Arena::CreateMaybeMessage<::UDM::topicList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace UDM {

// ===================================================================

class Node final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UDM.Node) */ {
 public:
  inline Node() : Node(nullptr) {}
  ~Node() override;
  explicit PROTOBUF_CONSTEXPR Node(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Node(const Node& from);
  Node(Node&& from) noexcept
    : Node() {
    *this = ::std::move(from);
  }

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }
  inline Node& operator=(Node&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Node& default_instance() {
    return *internal_default_instance();
  }
  static inline const Node* internal_default_instance() {
    return reinterpret_cast<const Node*>(
               &_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Node& a, Node& b) {
    a.Swap(&b);
  }
  inline void Swap(Node* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Node* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Node* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Node>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Node& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Node& from) {
    Node::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Node* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UDM.Node";
  }
  protected:
  explicit Node(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicNameFieldNumber = 1,
    kNameFieldNumber = 2,
    kTypeFieldNumber = 3,
    kLockedFieldNumber = 4,
  };
  // string topicName = 1;
  void clear_topicname();
  const std::string& topicname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_topicname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_topicname();
  PROTOBUF_NODISCARD std::string* release_topicname();
  void set_allocated_topicname(std::string* topicname);
  private:
  const std::string& _internal_topicname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_topicname(const std::string& value);
  std::string* _internal_mutable_topicname();
  public:

  // string Name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 type = 3;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // bool locked = 4;
  void clear_locked();
  bool locked() const;
  void set_locked(bool value);
  private:
  bool _internal_locked() const;
  void _internal_set_locked(bool value);
  public:

  // @@protoc_insertion_point(class_scope:UDM.Node)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topicname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t type_;
    bool locked_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_topicList_2eproto;
};
// -------------------------------------------------------------------

class topicList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UDM.topicList) */ {
 public:
  inline topicList() : topicList(nullptr) {}
  ~topicList() override;
  explicit PROTOBUF_CONSTEXPR topicList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  topicList(const topicList& from);
  topicList(topicList&& from) noexcept
    : topicList() {
    *this = ::std::move(from);
  }

  inline topicList& operator=(const topicList& from) {
    CopyFrom(from);
    return *this;
  }
  inline topicList& operator=(topicList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const topicList& default_instance() {
    return *internal_default_instance();
  }
  static inline const topicList* internal_default_instance() {
    return reinterpret_cast<const topicList*>(
               &_topicList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(topicList& a, topicList& b) {
    a.Swap(&b);
  }
  inline void Swap(topicList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(topicList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  topicList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<topicList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const topicList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const topicList& from) {
    topicList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(topicList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UDM.topicList";
  }
  protected:
  explicit topicList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodesFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // repeated .UDM.Node nodes = 2;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::UDM::Node* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UDM::Node >*
      mutable_nodes();
  private:
  const ::UDM::Node& _internal_nodes(int index) const;
  ::UDM::Node* _internal_add_nodes();
  public:
  const ::UDM::Node& nodes(int index) const;
  ::UDM::Node* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UDM::Node >&
      nodes() const;

  // int32 type = 1;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:UDM.topicList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UDM::Node > nodes_;
    int32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_topicList_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Node

// string topicName = 1;
inline void Node::clear_topicname() {
  _impl_.topicname_.ClearToEmpty();
}
inline const std::string& Node::topicname() const {
  // @@protoc_insertion_point(field_get:UDM.Node.topicName)
  return _internal_topicname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Node::set_topicname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.topicname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.Node.topicName)
}
inline std::string* Node::mutable_topicname() {
  std::string* _s = _internal_mutable_topicname();
  // @@protoc_insertion_point(field_mutable:UDM.Node.topicName)
  return _s;
}
inline const std::string& Node::_internal_topicname() const {
  return _impl_.topicname_.Get();
}
inline void Node::_internal_set_topicname(const std::string& value) {
  
  _impl_.topicname_.Set(value, GetArenaForAllocation());
}
inline std::string* Node::_internal_mutable_topicname() {
  
  return _impl_.topicname_.Mutable(GetArenaForAllocation());
}
inline std::string* Node::release_topicname() {
  // @@protoc_insertion_point(field_release:UDM.Node.topicName)
  return _impl_.topicname_.Release();
}
inline void Node::set_allocated_topicname(std::string* topicname) {
  if (topicname != nullptr) {
    
  } else {
    
  }
  _impl_.topicname_.SetAllocated(topicname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.topicname_.IsDefault()) {
    _impl_.topicname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.Node.topicName)
}

// string Name = 2;
inline void Node::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Node::name() const {
  // @@protoc_insertion_point(field_get:UDM.Node.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Node::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.Node.Name)
}
inline std::string* Node::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:UDM.Node.Name)
  return _s;
}
inline const std::string& Node::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Node::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Node::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Node::release_name() {
  // @@protoc_insertion_point(field_release:UDM.Node.Name)
  return _impl_.name_.Release();
}
inline void Node::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.Node.Name)
}

// int32 type = 3;
inline void Node::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t Node::_internal_type() const {
  return _impl_.type_;
}
inline int32_t Node::type() const {
  // @@protoc_insertion_point(field_get:UDM.Node.type)
  return _internal_type();
}
inline void Node::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void Node::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:UDM.Node.type)
}

// bool locked = 4;
inline void Node::clear_locked() {
  _impl_.locked_ = false;
}
inline bool Node::_internal_locked() const {
  return _impl_.locked_;
}
inline bool Node::locked() const {
  // @@protoc_insertion_point(field_get:UDM.Node.locked)
  return _internal_locked();
}
inline void Node::_internal_set_locked(bool value) {
  
  _impl_.locked_ = value;
}
inline void Node::set_locked(bool value) {
  _internal_set_locked(value);
  // @@protoc_insertion_point(field_set:UDM.Node.locked)
}

// -------------------------------------------------------------------

// topicList

// int32 type = 1;
inline void topicList::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t topicList::_internal_type() const {
  return _impl_.type_;
}
inline int32_t topicList::type() const {
  // @@protoc_insertion_point(field_get:UDM.topicList.type)
  return _internal_type();
}
inline void topicList::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void topicList::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:UDM.topicList.type)
}

// repeated .UDM.Node nodes = 2;
inline int topicList::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int topicList::nodes_size() const {
  return _internal_nodes_size();
}
inline void topicList::clear_nodes() {
  _impl_.nodes_.Clear();
}
inline ::UDM::Node* topicList::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:UDM.topicList.nodes)
  return _impl_.nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UDM::Node >*
topicList::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:UDM.topicList.nodes)
  return &_impl_.nodes_;
}
inline const ::UDM::Node& topicList::_internal_nodes(int index) const {
  return _impl_.nodes_.Get(index);
}
inline const ::UDM::Node& topicList::nodes(int index) const {
  // @@protoc_insertion_point(field_get:UDM.topicList.nodes)
  return _internal_nodes(index);
}
inline ::UDM::Node* topicList::_internal_add_nodes() {
  return _impl_.nodes_.Add();
}
inline ::UDM::Node* topicList::add_nodes() {
  ::UDM::Node* _add = _internal_add_nodes();
  // @@protoc_insertion_point(field_add:UDM.topicList.nodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UDM::Node >&
topicList::nodes() const {
  // @@protoc_insertion_point(field_list:UDM.topicList.nodes)
  return _impl_.nodes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UDM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_topicList_2eproto
