// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udmMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_udmMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_udmMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_udmMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_udmMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_udmMessage_2eproto;
namespace UDM {
class UDMMessage;
struct UDMMessageDefaultTypeInternal;
extern UDMMessageDefaultTypeInternal _UDMMessage_default_instance_;
}  // namespace UDM
PROTOBUF_NAMESPACE_OPEN
template<> ::UDM::UDMMessage* Arena::CreateMaybeMessage<::UDM::UDMMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace UDM {

// ===================================================================

class UDMMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UDM.UDMMessage) */ {
 public:
  inline UDMMessage() : UDMMessage(nullptr) {}
  ~UDMMessage() override;
  explicit PROTOBUF_CONSTEXPR UDMMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UDMMessage(const UDMMessage& from);
  UDMMessage(UDMMessage&& from) noexcept
    : UDMMessage() {
    *this = ::std::move(from);
  }

  inline UDMMessage& operator=(const UDMMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline UDMMessage& operator=(UDMMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UDMMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const UDMMessage* internal_default_instance() {
    return reinterpret_cast<const UDMMessage*>(
               &_UDMMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UDMMessage& a, UDMMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(UDMMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UDMMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UDMMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UDMMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UDMMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UDMMessage& from) {
    UDMMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UDMMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UDM.UDMMessage";
  }
  protected:
  explicit UDMMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicNameFieldNumber = 2,
    kVariableNameFieldNumber = 3,
    kVariableUnitFieldNumber = 4,
    kSourceNameFieldNumber = 5,
    kValueFieldNumber = 8,
    kMessageTypeFieldNumber = 1,
    kLockStatFieldNumber = 6,
    kTimestampFieldNumber = 7,
  };
  // string topicName = 2;
  void clear_topicname();
  const std::string& topicname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_topicname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_topicname();
  PROTOBUF_NODISCARD std::string* release_topicname();
  void set_allocated_topicname(std::string* topicname);
  private:
  const std::string& _internal_topicname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_topicname(const std::string& value);
  std::string* _internal_mutable_topicname();
  public:

  // string variableName = 3;
  void clear_variablename();
  const std::string& variablename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_variablename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_variablename();
  PROTOBUF_NODISCARD std::string* release_variablename();
  void set_allocated_variablename(std::string* variablename);
  private:
  const std::string& _internal_variablename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_variablename(const std::string& value);
  std::string* _internal_mutable_variablename();
  public:

  // string variableUnit = 4;
  void clear_variableunit();
  const std::string& variableunit() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_variableunit(ArgT0&& arg0, ArgT... args);
  std::string* mutable_variableunit();
  PROTOBUF_NODISCARD std::string* release_variableunit();
  void set_allocated_variableunit(std::string* variableunit);
  private:
  const std::string& _internal_variableunit() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_variableunit(const std::string& value);
  std::string* _internal_mutable_variableunit();
  public:

  // string sourceName = 5;
  void clear_sourcename();
  const std::string& sourcename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sourcename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sourcename();
  PROTOBUF_NODISCARD std::string* release_sourcename();
  void set_allocated_sourcename(std::string* sourcename);
  private:
  const std::string& _internal_sourcename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sourcename(const std::string& value);
  std::string* _internal_mutable_sourcename();
  public:

  // bytes value = 8;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // int32 message_type = 1;
  void clear_message_type();
  int32_t message_type() const;
  void set_message_type(int32_t value);
  private:
  int32_t _internal_message_type() const;
  void _internal_set_message_type(int32_t value);
  public:

  // int32 lockStat = 6;
  void clear_lockstat();
  int32_t lockstat() const;
  void set_lockstat(int32_t value);
  private:
  int32_t _internal_lockstat() const;
  void _internal_set_lockstat(int32_t value);
  public:

  // uint64 timestamp = 7;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:UDM.UDMMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topicname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr variablename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr variableunit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sourcename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    int32_t message_type_;
    int32_t lockstat_;
    uint64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_udmMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UDMMessage

// int32 message_type = 1;
inline void UDMMessage::clear_message_type() {
  _impl_.message_type_ = 0;
}
inline int32_t UDMMessage::_internal_message_type() const {
  return _impl_.message_type_;
}
inline int32_t UDMMessage::message_type() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.message_type)
  return _internal_message_type();
}
inline void UDMMessage::_internal_set_message_type(int32_t value) {
  
  _impl_.message_type_ = value;
}
inline void UDMMessage::set_message_type(int32_t value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.message_type)
}

// string topicName = 2;
inline void UDMMessage::clear_topicname() {
  _impl_.topicname_.ClearToEmpty();
}
inline const std::string& UDMMessage::topicname() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.topicName)
  return _internal_topicname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UDMMessage::set_topicname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.topicname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.topicName)
}
inline std::string* UDMMessage::mutable_topicname() {
  std::string* _s = _internal_mutable_topicname();
  // @@protoc_insertion_point(field_mutable:UDM.UDMMessage.topicName)
  return _s;
}
inline const std::string& UDMMessage::_internal_topicname() const {
  return _impl_.topicname_.Get();
}
inline void UDMMessage::_internal_set_topicname(const std::string& value) {
  
  _impl_.topicname_.Set(value, GetArenaForAllocation());
}
inline std::string* UDMMessage::_internal_mutable_topicname() {
  
  return _impl_.topicname_.Mutable(GetArenaForAllocation());
}
inline std::string* UDMMessage::release_topicname() {
  // @@protoc_insertion_point(field_release:UDM.UDMMessage.topicName)
  return _impl_.topicname_.Release();
}
inline void UDMMessage::set_allocated_topicname(std::string* topicname) {
  if (topicname != nullptr) {
    
  } else {
    
  }
  _impl_.topicname_.SetAllocated(topicname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.topicname_.IsDefault()) {
    _impl_.topicname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.UDMMessage.topicName)
}

// string variableName = 3;
inline void UDMMessage::clear_variablename() {
  _impl_.variablename_.ClearToEmpty();
}
inline const std::string& UDMMessage::variablename() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.variableName)
  return _internal_variablename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UDMMessage::set_variablename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.variablename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.variableName)
}
inline std::string* UDMMessage::mutable_variablename() {
  std::string* _s = _internal_mutable_variablename();
  // @@protoc_insertion_point(field_mutable:UDM.UDMMessage.variableName)
  return _s;
}
inline const std::string& UDMMessage::_internal_variablename() const {
  return _impl_.variablename_.Get();
}
inline void UDMMessage::_internal_set_variablename(const std::string& value) {
  
  _impl_.variablename_.Set(value, GetArenaForAllocation());
}
inline std::string* UDMMessage::_internal_mutable_variablename() {
  
  return _impl_.variablename_.Mutable(GetArenaForAllocation());
}
inline std::string* UDMMessage::release_variablename() {
  // @@protoc_insertion_point(field_release:UDM.UDMMessage.variableName)
  return _impl_.variablename_.Release();
}
inline void UDMMessage::set_allocated_variablename(std::string* variablename) {
  if (variablename != nullptr) {
    
  } else {
    
  }
  _impl_.variablename_.SetAllocated(variablename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.variablename_.IsDefault()) {
    _impl_.variablename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.UDMMessage.variableName)
}

// string variableUnit = 4;
inline void UDMMessage::clear_variableunit() {
  _impl_.variableunit_.ClearToEmpty();
}
inline const std::string& UDMMessage::variableunit() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.variableUnit)
  return _internal_variableunit();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UDMMessage::set_variableunit(ArgT0&& arg0, ArgT... args) {
 
 _impl_.variableunit_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.variableUnit)
}
inline std::string* UDMMessage::mutable_variableunit() {
  std::string* _s = _internal_mutable_variableunit();
  // @@protoc_insertion_point(field_mutable:UDM.UDMMessage.variableUnit)
  return _s;
}
inline const std::string& UDMMessage::_internal_variableunit() const {
  return _impl_.variableunit_.Get();
}
inline void UDMMessage::_internal_set_variableunit(const std::string& value) {
  
  _impl_.variableunit_.Set(value, GetArenaForAllocation());
}
inline std::string* UDMMessage::_internal_mutable_variableunit() {
  
  return _impl_.variableunit_.Mutable(GetArenaForAllocation());
}
inline std::string* UDMMessage::release_variableunit() {
  // @@protoc_insertion_point(field_release:UDM.UDMMessage.variableUnit)
  return _impl_.variableunit_.Release();
}
inline void UDMMessage::set_allocated_variableunit(std::string* variableunit) {
  if (variableunit != nullptr) {
    
  } else {
    
  }
  _impl_.variableunit_.SetAllocated(variableunit, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.variableunit_.IsDefault()) {
    _impl_.variableunit_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.UDMMessage.variableUnit)
}

// string sourceName = 5;
inline void UDMMessage::clear_sourcename() {
  _impl_.sourcename_.ClearToEmpty();
}
inline const std::string& UDMMessage::sourcename() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.sourceName)
  return _internal_sourcename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UDMMessage::set_sourcename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sourcename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.sourceName)
}
inline std::string* UDMMessage::mutable_sourcename() {
  std::string* _s = _internal_mutable_sourcename();
  // @@protoc_insertion_point(field_mutable:UDM.UDMMessage.sourceName)
  return _s;
}
inline const std::string& UDMMessage::_internal_sourcename() const {
  return _impl_.sourcename_.Get();
}
inline void UDMMessage::_internal_set_sourcename(const std::string& value) {
  
  _impl_.sourcename_.Set(value, GetArenaForAllocation());
}
inline std::string* UDMMessage::_internal_mutable_sourcename() {
  
  return _impl_.sourcename_.Mutable(GetArenaForAllocation());
}
inline std::string* UDMMessage::release_sourcename() {
  // @@protoc_insertion_point(field_release:UDM.UDMMessage.sourceName)
  return _impl_.sourcename_.Release();
}
inline void UDMMessage::set_allocated_sourcename(std::string* sourcename) {
  if (sourcename != nullptr) {
    
  } else {
    
  }
  _impl_.sourcename_.SetAllocated(sourcename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sourcename_.IsDefault()) {
    _impl_.sourcename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.UDMMessage.sourceName)
}

// int32 lockStat = 6;
inline void UDMMessage::clear_lockstat() {
  _impl_.lockstat_ = 0;
}
inline int32_t UDMMessage::_internal_lockstat() const {
  return _impl_.lockstat_;
}
inline int32_t UDMMessage::lockstat() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.lockStat)
  return _internal_lockstat();
}
inline void UDMMessage::_internal_set_lockstat(int32_t value) {
  
  _impl_.lockstat_ = value;
}
inline void UDMMessage::set_lockstat(int32_t value) {
  _internal_set_lockstat(value);
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.lockStat)
}

// uint64 timestamp = 7;
inline void UDMMessage::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t UDMMessage::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t UDMMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.timestamp)
  return _internal_timestamp();
}
inline void UDMMessage::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void UDMMessage::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.timestamp)
}

// bytes value = 8;
inline void UDMMessage::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& UDMMessage::value() const {
  // @@protoc_insertion_point(field_get:UDM.UDMMessage.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UDMMessage::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UDM.UDMMessage.value)
}
inline std::string* UDMMessage::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:UDM.UDMMessage.value)
  return _s;
}
inline const std::string& UDMMessage::_internal_value() const {
  return _impl_.value_.Get();
}
inline void UDMMessage::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* UDMMessage::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* UDMMessage::release_value() {
  // @@protoc_insertion_point(field_release:UDM.UDMMessage.value)
  return _impl_.value_.Release();
}
inline void UDMMessage::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UDM.UDMMessage.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace UDM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_udmMessage_2eproto
